fail_fast: false
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.9
  hooks:
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix, --config, pyproject.toml ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
        args: [ --config, pyproject.toml ]
